### ISSUE TITLE
Reserved space for root

### ISSUE THREAD

**Issue by grosbedos** [vincentg/Check-SNMP-plugins#2]
Hi,

In ext3, some disk space are reserved for root user.
If you check your free space, the plugin return 5% of free space, but just usuable for the root user.
For other user, the disk is already full.

How can i change your plugin to return free space for normal user?

Best regards,

Vincent.

**Comment by vincentg** [comment]
Hi Vincent, 

Currently, I just return the free space information given by the SNMP protocol.
But to solve this issue, I will plan to add a command line option to specify a percentage of space to add.
for instance "check_snmp_disk -R 5 ..."

The code change should be small, and I planned to work a little bit to issue a new release of the plugins to address a few issues I have been notified.

Thanks,

Vincent.

**Comment by grosbedos** [comment]
Hi,

Thanks for your answer,
I stay tune about a new commit ;)

Have a nice day!
