### ISSUE TITLE
check_snmp_disk returns OK if no disk is found 

### ISSUE THREAD

**Issue by schurzi** [vincentg/Check-SNMP-plugins#3]
Hi,

we use check_snmp_disk to monitor some NFS disks. Now we had the problem, that no NFS disk was mounted and the check returned OK. We feel, that this is a Bug.

**Comment by schurzi** [comment]
I have already written a modified check of the alert status. But I don't know how to upload a patch. Once I find out, I will attach it.

**Comment by vincentg** [comment]
Merged your pull request, thanks
